services:
  caoson_report_reverse_proxy_service:
    build:
      context: ./reverse_proxy
    image: ${REGISTRY}/caoson_report_reverse_proxy_img:${VERSION}

  caoson_report_backend_service:
    build:
      context: ./be
    image: ${REGISTRY}/caoson_report_backend_img:${VERSION}

  caoson_report_frontend_service:
    build:
      context: ./fe-modul-report
    image: ${REGISTRY}/caoson_report_frontend_img:${VERSION}