###### Build Docker Images and push to DockerHub Repository ######
### Rerferences:
# 1. Compose build specs: https://docs.docker.com/compose/compose-file/build/
# Run the commands:
# a. Build: $ docker compose -f docker-compose-build.yaml build --parallel
# b. Push:  $ docker compose -f docker-compose-build.yaml push
#####
services:
  hatu/report_reverse_proxy_service:
    build:
      context: ./reverse_proxy
    image: ${REGISTRY}/hatu/report_reverse_proxy_img:${VERSION}

  hatu/report_backend_service:
    build:
      context: ./be
    image: ${REGISTRY}/hatu/report_backend_img:${VERSION}

  hatu/report_frontend_service:
    build:
      context: ./fe-modul-report
    image: ${REGISTRY}/hatu/report_frontend_img:${VERSION}
