services:
  kvdabac_report_reverse_proxy_service:
    image: ${REGISTRY}/kvdabac_report_reverse_proxy_img:${VERSION}
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "6969:8888"
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backnet
      - frontnet
    depends_on:
      - kvdabac_report_backend_service
      - kvdabac_report_frontend_service

  kvdabac_report_backend_service:
    env_file:
      - .env_backend
    image: ${REGISTRY}/kvdabac_report_backend_img:${VERSION}
    depends_on:
      kvdabac_postgres:
        condition: service_healthy
    ports:
      - "8585:8080"
    networks:
      - backnet
    restart: unless-stopped

  kvdabac_report_frontend_service:
    image: ${REGISTRY}/kvdabac_report_frontend_img:${VERSION}
    # target: development
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # For development only, to synced src code to container
      - /usr/src/app/node_modules
    # restart: always
    networks:
      - frontnet

  kvdabac_postgres:
    container_name: kvdabac_pg_report_2211
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=report
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - kvdabac_report_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - backnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  kvdabac_pgadmin:
    container_name: kvdabac_pgadmin_report_2211
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - kvdabac_report_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5052:80"
    restart: unless-stopped

volumes:
  kvdabac_report_postgres_data: # ✅ Cho postgres
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/kvdabac_report_postgres_data
      o: bind

  kvdabac_report_pgadmin_data: # ✅ Cho pgadmin (thêm mới)
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/kvdabac_report_pgadmin_data
      o: bind

networks:
  backnet:
  frontnet:
