services:
  caoson_report_reverse_proxy_service:
    image: ${REGISTRY}/caoson_report_reverse_proxy_img:${VERSION}
    ports:
      - "1104:8888"   # ← port mới, tránh conflict
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backnet
      - frontnet
    depends_on:
      - caoson_report_backend_service
      - caoson_report_frontend_service

  caoson_report_backend_service:
    env_file:
      - .env_backend
    image: ${REGISTRY}/caoson_report_backend_img:${VERSION}
    depends_on:
      - caoson_postgres
    ports:
      - "2612:8080"   # ← port mới
    networks:
      - backnet
    restart: unless-stopped

  caoson_report_frontend_service:
    image: ${REGISTRY}/caoson_report_frontend_img:${VERSION}
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /usr/src/app/node_modules
    networks:
      - frontnet

  caoson_postgres:
    container_name: pg_caoson_report_2211
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=report
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - caoson_report_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_caoson_report_2211
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - caoson_report_pgadmin_data:/var/lib/pgadmin
    ports:
      - "2604:80"     # ← port mới
    networks:
      - backnet

volumes:
  caoson_report_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/caoson_report_postgres_data
      o: bind

  caoson_report_pgadmin_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/caoson_report_pgadmin_data
      o: bind

networks:
  backnet:
  frontnet:
