services:
  hatu_report_reverse_proxy_service:
    image: ${REGISTRY}/hatu_report_reverse_proxy_img:${VERSION}
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "6262:8888"
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backnet
      - frontnet
    depends_on:
      - hatu_report_backend_service
      - hatu_report_frontend_service

  hatu_report_backend_service:
    env_file:
      - .env_backend
    image: ${REGISTRY}/hatu_report_backend_img:${VERSION}
    depends_on:
      - hatu_postgres
    ports:
      - "8686:8080"
    networks:
      - backnet
    restart: unless-stopped

  hatu_report_frontend_service:
    image: ${REGISTRY}/hatu_report_frontend_img:${VERSION}
    # target: development
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # For development only, to synced src code to container
      - /usr/src/app/node_modules
    # restart: always
    networks:
      - frontnet

  hatu_postgres:
    container_name: hatu_pg_report_2211
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=report
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - hatu_report_postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    restart: unless-stopped
    networks:
      - backnet

  hatu_pgadmin:
    container_name: hatu_pgadmin_report_2211
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - hatu_report_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5053:80"
    restart: unless-stopped
    networks:
      - backnet

volumes:
  hatu_report_postgres_data: # ✅ Cho postgres
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/hatu_report_postgres_data
      o: bind

  hatu_report_pgadmin_data: # ✅ Cho pgadmin (thêm mới)
    driver: local
    driver_opts:
      type: none
      device: /mnt/hdd/hatu_report_pgadmin_data
      o: bind

networks:
  backnet:
  frontnet:
