#!/bin/bash
# Start the application in the staging environment
# Docker compose for deployment - tenant-aware
# Called by CI/CD after deploy files are SCP'd to server
# The .env_tenant file is generated by CI/CD pipeline

COMPOSE_FILE="staging-docker-compose.yaml"
ENV_FILE=".env_tenant"

if [ ! -f "$ENV_FILE" ]; then
  echo "❌ Không tìm thấy $ENV_FILE. CI/CD có copy file này chưa?"
  exit 1
fi

TENANT=$(grep "^TENANT=" "$ENV_FILE" | cut -d= -f2)
PROJECT_NAME="${TENANT:-tenant}_staging"
echo "🚀 Deploying tenant: ${TENANT} (staging)"

docker compose -p "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" down
docker compose -p "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull
nohup docker compose -p "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d > deploy.log 2>&1 &
docker image prune -f
docker images | grep "$TENANT"