services:
  #backend:
  #fontend:
  #reverse_proxy

  postgres:
    container_name: pg_report_2211
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=report
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg_report_2211:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_report_2211
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_report_2211:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pg_report_2211:
  pgadmin_report_2211: