WITH BIEN_CHE AS (
    SELECT MA_PBAN, COUNT(*) AS TONG_NHAN_LUC
    FROM staging_lenhsx.DM_CBCNV
    WHERE ACTIVE = true
    GROUP BY MA_PBAN
),
DI_LAM AS (
    SELECT
        v.MA_PBAN,
        v.MA_CA,
        v.MA_CBCNV,
        cvu.MA_NHOM_CVU
    FROM staging_lenhsx.LENHSX_VIEW v
    LEFT JOIN staging_lenhsx.DM_CVU cvu ON cvu.MA_CVU = v.MA_CVU
    WHERE CAST(v.NGAY_VAO_SO AS DATE) = :ngayBaoCao
    GROUP BY v.MA_PBAN, v.MA_CA, v.MA_CBCNV, cvu.MA_NHOM_CVU
),
DI_LAM_TONG_HOP AS (
    SELECT
        MA_PBAN,
        MA_CA,
        COUNT(DISTINCT MA_CBCNV) AS TONG_DI_LAM,
        COUNT(DISTINCT CASE WHEN MA_NHOM_CVU = '02' THEN MA_CBCNV END) AS TLO_DI_LAM,
        COUNT(DISTINCT CASE WHEN MA_NHOM_CVU IN ('03','04') THEN MA_CBCNV END) AS CODIEN,
        COUNT(DISTINCT CASE WHEN MA_NHOM_CVU = '05' THEN MA_CBCNV END) AS QLY_PVU
    FROM DI_LAM
    GROUP BY MA_PBAN, MA_CA
),
VANG_MAT AS (
    SELECT b.MA_PBAN, b.MA_CA, b.MA_CBCNV, b.MA_CONG, b.MA_NHOM_CVU
    FROM staging_lenhsx.BCSC_NGHI_VIEW b
    WHERE CAST(b.NGAY_VAO_SO AS DATE) = :ngayBaoCao
),
VANG_MAT_TONG_HOP AS (
    SELECT
        MA_PBAN,
        MA_CA,
        COUNT(DISTINCT MA_CBCNV) AS TONG_VANG,
        COUNT(DISTINCT CASE WHEN MA_CONG = 'OM'   THEN MA_CBCNV END) AS OM,
        COUNT(DISTINCT CASE WHEN MA_CONG = 'PH'   THEN MA_CBCNV END) AS PH,
        COUNT(DISTINCT CASE WHEN MA_CONG = 'TTUC' THEN MA_CBCNV END) AS TTUC,
        COUNT(DISTINCT CASE WHEN MA_CONG = 'H2'   THEN MA_CBCNV END) AS H2,
        COUNT(DISTINCT CASE WHEN MA_CONG = 'VO'   THEN MA_CBCNV END) AS VO,
        COUNT(DISTINCT CASE WHEN MA_NHOM_CVU = '02' THEN MA_CBCNV END) AS TLO_VANG_TRONG_NGAY
    FROM VANG_MAT
    GROUP BY MA_PBAN, MA_CA
),
DANH_SACH_CA AS (
    SELECT DISTINCT MA_PBAN, MA_CA FROM DI_LAM_TONG_HOP
    UNION
    SELECT DISTINCT MA_PBAN, MA_CA FROM VANG_MAT_TONG_HOP
)
SELECT
    p.MA_PBAN,
    p.TEN_PBAN,
    p.MA_NHOM_PBAN,
    np.TEN_NHOM_PBAN,
    n.MA_CA,
    ca.TEN_CA,
    COALESCE(bc.TONG_NHAN_LUC,0)   AS TONG_NHAN_LUC,
    COALESCE(d.TONG_DI_LAM, 0)      AS TONG_DI_LAM,
    COALESCE(d.TLO_DI_LAM, 0)       AS TLO_DI_LAM,
    COALESCE(d.CODIEN, 0)           AS CODIEN,
    COALESCE(d.QLY_PVU, 0)          AS QLY_PVU,
    COALESCE(v.TONG_VANG, 0)        AS TONG_VANG,
    COALESCE(v.OM, 0)   AS OM,
    COALESCE(v.PH, 0)   AS PH,
    COALESCE(v.TTUC, 0) AS TTUC,
    COALESCE(v.H2, 0)   AS H2,
    COALESCE(v.VO, 0)   AS VO,
    COALESCE(v.TLO_VANG_TRONG_NGAY, 0) AS TLO_VANG_TRONG_NGAY
FROM staging_lenhsx.DM_PBAN p
LEFT JOIN staging_lenhsx.DM_NHOM_PBAN np ON np.MA_NHOM_PBAN = p.MA_NHOM_PBAN
LEFT JOIN BIEN_CHE bc         ON bc.MA_PBAN = p.MA_PBAN
LEFT JOIN DANH_SACH_CA n      ON n.MA_PBAN = p.MA_PBAN
LEFT JOIN DI_LAM_TONG_HOP d   ON d.MA_PBAN = n.MA_PBAN AND d.MA_CA = n.MA_CA
LEFT JOIN VANG_MAT_TONG_HOP v ON v.MA_PBAN = n.MA_PBAN AND v.MA_CA = n.MA_CA
LEFT JOIN staging_lenhsx.DM_CA ca        ON ca.MA_CA = n.MA_CA
WHERE p.ACTIVE = true AND p.MA_NHOM_PBAN <> 'I'
ORDER BY p.MA_NHOM_PBAN, p.MA_PBAN, n.MA_CA;

