name: Deploy for release version

on:
  push:
    branches:
      - dev/caoson2

env:
  WEBAPP_NAME: data-lake
  WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "20.x"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Working Directory
        run: pwd

      - name: Create an .env file in frontend for building image
        run: |
          echo "VITE_API=${{ secrets.VITE_API }}" > ./fe-modul-report/.env

      - name: List Files
        run: ls -laR

      - name: Run Makefiles with Secrets to build anh push docker images to dockerhub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          make staging
          ls -al .env
          cat .env
          cp .env deployment/staging/         # ← đổi

      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}        # ← đổi
          username: ${{ secrets.STAGING_USER }}    # ← đổi
          key: ${{ secrets.STAGING_SSH_KEY }}      # ← đổi
          port: ${{ secrets.STAGING_PORT }}        # ← đổi
          script: |
            mkdir -p /home/${{ secrets.STAGING_USER }}/data-lake/caoson/deployment/staging  # ← đổi

      - name: Transfer docker-compose file to VPS for deployment
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGING_HOST }}        # ← đổi
          username: ${{ secrets.STAGING_USER }}    # ← đổi
          key: ${{ secrets.STAGING_SSH_KEY }}      # ← đổi
          port: ${{ secrets.STAGING_PORT }}        # ← đổi
          source: deployment/staging/*             # ← đổi
          target: "/home/${{ secrets.STAGING_USER }}/data-lake/caoson/deployment/staging"  # ← đổi
          strip_components: 2

      - name: Clean up containers and stuff via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}        # ← đổi
          username: ${{ secrets.STAGING_USER }}    # ← đổi
          key: ${{ secrets.STAGING_SSH_KEY }}      # ← đổi
          port: ${{ secrets.STAGING_PORT }}        # ← đổi
          script: |
            cd /home/${{ secrets.STAGING_USER }}/data-lake/caoson/deployment/staging  # ← đổi
            pwd
            ls -al
            docker image prune -f
            docker compose -f staging-docker-compose.yaml down  # ← đổi
            docker ps

      - name: Deploy to release via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}        # ← đổi
          username: ${{ secrets.STAGING_USER }}    # ← đổi
          key: ${{ secrets.STAGING_SSH_KEY }}      # ← đổi
          port: ${{ secrets.STAGING_PORT }}        # ← đổi
          script: |
            cd /home/${{ secrets.STAGING_USER }}/data-lake/caoson/deployment/staging  # ← đổi
            docker image prune -f
            chmod +x start-app.sh
            ./start-app.sh